# Generated by Django 2.0.2 on 2018-03-20 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_activity_comment_ingredient_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'managed': True, 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
