# Generated by Django 2.0.2 on 2018-03-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20180320_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='veg',
            field=models.BooleanField(default=False),
        ),
    ]
