# Generated by Django 2.0.2 on 2018-03-24 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20180324_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='complaints',
        ),
        migrations.AddField(
            model_name='complaint',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
    ]
